export default {
    Cafe: require('../assets/categoryIcons/Cafe.png'),
    Donate: require('../assets/categoryIcons/Donate.png'),
    Education: require('../assets/categoryIcons/Education.png'),
    Electronics: require('../assets/categoryIcons/Electronics.png'),
    Fuel: require('../assets/categoryIcons/Fuel.png'),
    Gifts: require('../assets/categoryIcons/Gifts.png'),
    Groceries: require('../assets/categoryIcons/Groceries.png'),
    Health: require('../assets/categoryIcons/Health.png'),
    Institute: require('../assets/categoryIcons/Institute.png'),
    Laundry: require('../assets/categoryIcons/Laundry.png'),
    Liquor: require('../assets/categoryIcons/Liquor.png'),
    Maintenance: require('../assets/categoryIcons/Maintenance.png'),
    Money: require('../assets/categoryIcons/Money.png'),
    Party: require('../assets/categoryIcons/Party.png'),
    Restaurant: require('../assets/categoryIcons/Restaurant.png'),
    Savings: require('../assets/categoryIcons/Savings.png'),
    SelfDevelopment: require('../assets/categoryIcons/SelfDevelopment.png'),
    Sport: require('../assets/categoryIcons/Sport.png'),
    Transportation: require('../assets/categoryIcons/Transportation.png'),
  };