export default {
    home: require('../assets/icons/home.png'),
    report: require('../assets/icons/report.png'),
    homeFocused: require('../assets/icons/homeFocused.png'),
    reportFocused: require('../assets/icons/reportFocused.png'),
    Balance: require('../assets/icons/Balance.png'),
    Expenses: require('../assets/icons/Expenses.png'),
    Income: require('../assets/icons/Income.png'),
    Logo: require('../assets/icons/Logo.png'),
    LeftArrow: require('../assets/icons/LeftArrow.png'),
    RightArrow: require('../assets/icons/RightArrow.png'),
    calendar: require('../assets/icons/calendar.png'),
    addPlus: require('../assets/icons/addPlus.png'),
    settings: require('../assets/icons/settings.png'),
    settingsFocused: require('../assets/icons/settingsFocused.png'),
    Currency: require('../assets/icons/Currency.png'),
    Language: require('../assets/icons/Language.png'),
    About: require('../assets/icons/About.png'),
  };